'use strict';

var Colors = {

  YOUNI_PRIMARY: '#02A9EB',
  TRENDING_PRIMARY: '#FF2A00',
  EXPLORE_PRIMARY: '#03A361',

  FADED_YOUNI_PRIMARY: '#89DAFA',
  LIGHT_YOUNI_PURPLE: '#E3E8FD',
  DARK_GRAY: '#1E2022',
  MED_GRAY: '#9B9B9B',
  LIGHT_GRAY: '#EAEAEA',
  BORDER_POP: '#D6D6D6',
  WHITE_SMOKE: '#FAFAFA'

};

module.exports = Colors;
