'use strict';

var Colors = {

  YOUNI_PRIMARY_PURPLE: '#5C7CFF',
  FADED_YOUNI_PRIMARY_PURPLE: '#9DB0FF',
  LIGHT_YOUNI_PURPLE: '#E3E8FD',
  DARK_GRAY: '#1E2022',
  MED_GRAY: '#9B9B9B',
  LIGHT_GRAY: '#EAEAEA',
  BORDER_POP: '#D6D6D6',
  WHITE_SMOKE: '#FAFAFA'

};

module.exports = Colors;
